Checking e2e build  succeeded
knative/build-templates pull request #89
Opened 2019-02-01 12:42 UTC by zouyee

Checking e2e build  succeeded

2019-02-04 13:38 UTC, zouyee commented
/cc @vdemeester

2019-02-04 15:31 UTC, vdemeester reviewed
/ok-to-test

2019-02-04 15:31 UTC, vdemeester commented on test/e2e-tests.sh
>    # TODO(adrcunha): Add proper verification.
This would need to be removed :angel:

2019-02-04 15:33 UTC, vdemeester commented
/ok-to-test

2019-02-11 07:05 UTC, zouyee commented on test/e2e-tests.sh
>    # TODO(adrcunha): Add proper verification.
ping!

2019-02-11 21:46 UTC, jessiezcc commented on test/e2e-tests.sh
> +     echo "waiting for build was successed."
how about "waiting for build to be successful"?

2019-03-06 14:38 UTC, ImJasonH commented
cc @adrcunha as resident bash expert and original TODO author

2019-03-06 17:14 UTC, adrcunha requested changes

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +     if [ $? -ne 1 ]; then
-eq 0

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +  done
Add some progress indicator here, I'm not sure how long the operation will take.

```
echo -n "."
```

Prior art:

https://github.com/knative/test-infra/blob/master/scripts/library.sh#L176

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +  done
Shouldn't you fail the test if the build didn't succeed? Otherwise, this check adds no value.

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +     kubectl get build buildpack-build -o 'jsonpath={.status.conditions[?(@.type=="Succeeded")].status}'  1>/dev/null 2>&1
I assume Jason agrees with this check?

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +  echo "Checking that build was successed:"
```suggestion
  echo -n "Waiting for build to finish"
```

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
>    # Wait 5s for processing to start
I believe that you can remove this sleep now, since you're checking for a successful build.

2019-03-06 17:14 UTC, adrcunha commented on test/e2e-tests.sh
> +     echo "The build was successed."
```suggestion
     echo -e "\nBuild succeeded."
```

2026-01-05 12:16 UTC, closed without merging